export const USER = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
  TOGGLE_AUTH_IN_PROGRESS: 'TOGGLE_AUTH_IN_PROGRESS'
};

export const PRODUCT = {
  SET_CURRENT_PRODUCT_ITEM: 'SET_CURRENT_PRODUCT_ITEM',
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  TOGGLE_REQUEST_IN_PROGRESS: 'TOGGLE_REQUEST_IN_PROGRESS'
};